export const nft_infos = [
  {
    player: `Lionel Messi`,
    season: `2011-2012`,
    team: `FC Barcelona`,
    card_pack: 2,
    card_color: 0,
    team_record: 'Copa Del Rey',
    man_record: '2012 Ballon dor, La Liga Top scorer, UEFA Champions League Top Scorer',
    img_url:
      'https://gateway.pinata.cloud/ipfs/QmVGZEoL8pzxfKwfj68GHtBScaGyPkX2REs4KuytewvLJP?filename=1-1.png',
  },
  {
    player: `Lionel Messi`,
    season: `2011-2012`,
    team: `FC Barcelona`,
    card_pack: 2,
    card_color: 1,
    team_record: 'Copa Del Rey',
    man_record: '2012 Ballon dor, La Liga Top scorer, UEFA Champions League Top Scorer',
    img_url:
      'https://gateway.pinata.cloud/ipfs/QmQx4ZDvfQTb8Dbi4ppVAzF2su7cHHuNnLGxnRitika9pV?filename=1-2.png',
  },
  {
    player: `Lionel Messi`,
    season: `2011-2012`,
    team: `FC Barcelona`,
    card_pack: 2,
    card_color: 2,
    team_record: 'Copa Del Rey',
    man_record: '2012 Ballon dor, La Liga Top scorer, UEFA Champions League Top Scorer',
    img_url:
      'https://gateway.pinata.cloud/ipfs/QmPer2sd2KCsPytPuSxZfP4fZThNVPnsX57fU8p897XvsD?filename=1-3.png',
  },
  {
    player: `Lionel Messi`,
    season: `2022 world cup`,
    team: `Argentina`,
    card_pack: 2,
    card_color: 0,
    team_record: '2022 World Cup',
    man_record: '2023 Ballon dor , 2022 World Cup Golden Ball',
    img_url:
      'https://gateway.pinata.cloud/ipfs/QmRWN7JbjL6w7aotVPiiFKf7ep6QSpcXeKa6fjfu9Vryon?filename=2-1.png',
  },
  {
    player: `Lionel Messi`,
    season: `2011-2012`,
    team: `Argentina`,
    card_pack: 2,
    card_color: 1,
    team_record: '2022 World Cup',
    man_record: '2023 Ballon dor , 2022 World Cup Golden Ball',
    img_url:
      'https://gateway.pinata.cloud/ipfs/QmTurre7smy3Y2Z4aYpHeDdztAnYHMwY6EAeem3tPMTVju?filename=2-2.png',
  },
  {
    player: `Lionel Messi`,
    season: `2011-2012`,
    team: `Argentina`,
    card_pack: 2,
    card_color: 2,
    team_record: '2022 World Cup',
    man_record: '2023 Ballon dor , 2022 World Cup Golden Ball',
    img_url:
      'https://gateway.pinata.cloud/ipfs/QmNjNckg6GbJF4CaJNeUtFG1REnEgP9d8hEK7zMZJjNuJ3?filename=2-3.png',
  },
  {
    player: `Lionel Messi`,
    season: `2014-2015`,
    team: `FC Barcelona`,
    card_pack: 2,
    card_color: 0,
    team_record: 'La Liga, UEFA Champions League, Copa Del Rey',
    man_record: '2015 Ballon dor , UEFA Champions League Top Scorer',
    img_url:
      'https://gateway.pinata.cloud/ipfs/QmSp1ZxXTiGVSBpoE2VQ4csj1gGEBDicRb2HNvNnJCyQxZ/3-1.png',
  },
  {
    player: `Lionel Messi`,
    season: `2014-2015`,
    team: `FC Barcelona`,
    card_pack: 2,
    card_color: 1,
    team_record: 'La Liga, UEFA Champions League, Copa Del Rey',
    man_record: '2015 Ballon dor , UEFA Champions League Top Scorer',
    img_url:
      'https://gateway.pinata.cloud/ipfs/QmSp1ZxXTiGVSBpoE2VQ4csj1gGEBDicRb2HNvNnJCyQxZ/3-2.png',
  },
  {
    player: `Lionel Messi`,
    season: `2014-2015`,
    team: `FC Barcelona`,
    card_pack: 2,
    card_color: 2,
    team_record: 'La Liga, UEFA Champions League, Copa Del Rey',
    man_record: '2015 Ballon dor , UEFA Champions League Top Scorer',
    img_url:
      'https://gateway.pinata.cloud/ipfs/QmSp1ZxXTiGVSBpoE2VQ4csj1gGEBDicRb2HNvNnJCyQxZ/3-3.png',
  },
  {
    player: `Cristiano Ronaldo`,
    season: `2007-2008`,
    team: `Manchester United`,
    card_pack: 2,
    card_color: 0,
    team_record: 'Premier League, UEFA Champions League',
    man_record: '2008 Ballon dor ,UEFA Champions League Top Scorer, Premeir League Top Scorer',
    img_url:
      'https://gateway.pinata.cloud/ipfs/QmSp1ZxXTiGVSBpoE2VQ4csj1gGEBDicRb2HNvNnJCyQxZ/4-1.png',
  },
  {
    player: `Cristiano Ronaldo`,
    season: `2007-2008`,
    team: `Manchester United`,
    card_pack: 2,
    card_color: 1,
    team_record: 'Premier League, UEFA Champions League',
    man_record: '2008 Ballon dor ,UEFA Champions League Top Scorer, Premeir League Top Scorer',
    img_url:
      'https://gateway.pinata.cloud/ipfs/QmSp1ZxXTiGVSBpoE2VQ4csj1gGEBDicRb2HNvNnJCyQxZ/4-2.png',
  },
  {
    player: `Cristiano Ronaldo`,
    season: `2007-2008`,
    team: `Manchester United`,
    card_pack: 2,
    card_color: 2,
    team_record: 'Premier League, UEFA Champions League',
    man_record: '2008 Ballon dor ,UEFA Champions League Top Scorer, Premeir League Top Scorer',
    img_url:
      'https://gateway.pinata.cloud/ipfs/QmSp1ZxXTiGVSBpoE2VQ4csj1gGEBDicRb2HNvNnJCyQxZ/4-3.png',
  },
  {
    player: `Cristiano Ronaldo`,
    season: `2011-2012`,
    team: `Real Madrid`,
    card_pack: 2,
    card_color: 0,
    team_record: 'La Liga',
    man_record: '',
    img_url:
      'https://gateway.pinata.cloud/ipfs/QmSp1ZxXTiGVSBpoE2VQ4csj1gGEBDicRb2HNvNnJCyQxZ/5-1.png',
  },
  {
    player: `Cristiano Ronaldo`,
    season: `2011-2012`,
    team: `Real Madrid`,
    card_pack: 2,
    card_color: 1,
    team_record: 'La Liga',
    man_record: '',
    img_url:
      'https://gateway.pinata.cloud/ipfs/QmSp1ZxXTiGVSBpoE2VQ4csj1gGEBDicRb2HNvNnJCyQxZ/5-2.png',
  },
  {
    player: `Cristiano Ronaldo`,
    season: `2011-2012`,
    team: `Real Madrid`,
    card_pack: 2,
    card_color: 2,
    team_record: 'La Liga',
    man_record: '',
    img_url:
      'https://gateway.pinata.cloud/ipfs/QmSp1ZxXTiGVSBpoE2VQ4csj1gGEBDicRb2HNvNnJCyQxZ/5-3.png',
  },
  {
    player: `Cristiano Ronaldo`,
    season: `2016 Euro`,
    team: `Portugal`,
    card_pack: 2,
    card_color: 0,
    team_record: '2016 Euro',
    man_record: '2017 Ballon dor , 2016 Euro Sliver Boot',
    img_url:
      'https://gateway.pinata.cloud/ipfs/QmSp1ZxXTiGVSBpoE2VQ4csj1gGEBDicRb2HNvNnJCyQxZ/6-1.png',
  },
  {
    player: `Cristiano Ronaldo`,
    season: `2016 Euro`,
    team: `Portugal`,
    card_pack: 2,
    card_color: 1,
    team_record: '2016 Euro',
    man_record: '2017 Ballon dor , 2016 Euro Sliver Boot',
    img_url:
      'https://gateway.pinata.cloud/ipfs/QmSp1ZxXTiGVSBpoE2VQ4csj1gGEBDicRb2HNvNnJCyQxZ/6-2.png',
  },
  {
    player: `Cristiano Ronaldo`,
    season: `2016 Euro`,
    team: `Portugal`,
    card_pack: 2,
    card_color: 2,
    team_record: '2016 Euro',
    man_record: '2017 Ballon dor , 2016 Euro Sliver Boot',
    img_url:
      'https://gateway.pinata.cloud/ipfs/QmSp1ZxXTiGVSBpoE2VQ4csj1gGEBDicRb2HNvNnJCyQxZ/6-3.png',
  },
  {
    player: `Son`,
    season: `2021-2022`,
    team: `Tottenham`,
    card_pack: 2,
    card_color: 0,
    team_record: '',
    man_record: 'Premeir League Top Scorer',
    img_url:
      'https://gateway.pinata.cloud/ipfs/QmSp1ZxXTiGVSBpoE2VQ4csj1gGEBDicRb2HNvNnJCyQxZ/7-1.png',
  },
  {
    player: `Son`,
    season: `2021-2022`,
    team: `Tottenham`,
    card_pack: 2,
    card_color: 1,
    team_record: '',
    man_record: 'Premeir League Top Scorer',
    img_url:
      'https://gateway.pinata.cloud/ipfs/QmSp1ZxXTiGVSBpoE2VQ4csj1gGEBDicRb2HNvNnJCyQxZ/7-2.png',
  },
  {
    player: `Son`,
    season: `2021-2022`,
    team: `Tottenham`,
    card_pack: 2,
    card_color: 2,
    team_record: '',
    man_record: 'Premeir League Top Scorer',
    img_url:
      'https://gateway.pinata.cloud/ipfs/QmSp1ZxXTiGVSBpoE2VQ4csj1gGEBDicRb2HNvNnJCyQxZ/7-3.png',
  },
  {
    player: `Cha boom`,
    season: `1979-1980`,
    team: `Frankfurt`,
    card_pack: 2,
    card_color: 0,
    team_record: 'UEFA Cup',
    man_record: '',
    img_url:
      'https://gateway.pinata.cloud/ipfs/QmSp1ZxXTiGVSBpoE2VQ4csj1gGEBDicRb2HNvNnJCyQxZ/8-1.png',
  },
  {
    player: `Cha boom`,
    season: `1979-1980`,
    team: `Frankfurt`,
    card_pack: 2,
    card_color: 1,
    team_record: 'UEFA Cup',
    man_record: '',
    img_url:
      'https://gateway.pinata.cloud/ipfs/QmSp1ZxXTiGVSBpoE2VQ4csj1gGEBDicRb2HNvNnJCyQxZ/8-2.png',
  },
  {
    player: `Cha boom`,
    season: `1979-1980`,
    team: `Frankfurt`,
    card_pack: 2,
    card_color: 2,
    team_record: 'UEFA Cup',
    man_record: '',
    img_url:
      'https://gateway.pinata.cloud/ipfs/QmSp1ZxXTiGVSBpoE2VQ4csj1gGEBDicRb2HNvNnJCyQxZ/8-3.png',
  },
  {
    player: `Karim Benzema`,
    season: `2021-2022`,
    team: `Real Madrid`,
    card_pack: 2,
    card_color: 0,
    team_record: 'UEFA Champions League, La Liga',
    man_record: '2022 Ballon dor, UEFA Champions League Top Scorer',
    img_url:
      'https://gateway.pinata.cloud/ipfs/QmSp1ZxXTiGVSBpoE2VQ4csj1gGEBDicRb2HNvNnJCyQxZ/9-1.png',
  },
  {
    player: `Karim Benzema`,
    season: `2021-2022`,
    team: `Real Madrid`,
    card_pack: 2,
    card_color: 1,
    team_record: 'UEFA Champions League, La Liga',
    man_record: '2022 Ballon dor, UEFA Champions League Top Scorer',
    img_url:
      'https://gateway.pinata.cloud/ipfs/QmSp1ZxXTiGVSBpoE2VQ4csj1gGEBDicRb2HNvNnJCyQxZ/9-2.png',
  },
  {
    player: `Karim Benzema`,
    season: `2021-2022`,
    team: `Real Madrid`,
    card_pack: 2,
    card_color: 2,
    team_record: 'UEFA Champions League, La Liga',
    man_record: '2022 Ballon dor, UEFA Champions League Top Scorer',
    img_url:
      'https://gateway.pinata.cloud/ipfs/QmSp1ZxXTiGVSBpoE2VQ4csj1gGEBDicRb2HNvNnJCyQxZ/9-3.png',
  },
  {
    player: `Luis Suarez`,
    season: `2015-2016`,
    team: `FC Barcelona`,
    card_pack: 2,
    card_color: 0,
    team_record: 'La Liga',
    man_record: 'La Liga Top Scorer',
    img_url:
      'https://gateway.pinata.cloud/ipfs/QmSp1ZxXTiGVSBpoE2VQ4csj1gGEBDicRb2HNvNnJCyQxZ/10-1.png',
  },
  {
    player: `Luis Suarez`,
    season: `2015-2016`,
    team: `FC Barcelona`,
    card_pack: 2,
    card_color: 1,
    team_record: 'La Liga',
    man_record: 'La Liga Top Scorer',
    img_url:
      'https://gateway.pinata.cloud/ipfs/QmSp1ZxXTiGVSBpoE2VQ4csj1gGEBDicRb2HNvNnJCyQxZ/10-2.png',
  },
  {
    player: `Luis Suarez`,
    season: `2015-2016`,
    team: `FC Barcelona`,
    card_pack: 2,
    card_color: 2,
    team_record: 'La Liga',
    man_record: 'La Liga Top Scorer',
    img_url:
      'https://gateway.pinata.cloud/ipfs/QmSp1ZxXTiGVSBpoE2VQ4csj1gGEBDicRb2HNvNnJCyQxZ/10-3.png',
  },
  {
    player: `Kaka`,
    season: `2006-2007`,
    team: `AC Millan`,
    card_pack: 1,
    card_color: 0,
    team_record: 'UEFA Champions League',
    man_record: '2007 Ballon dor, UEFA Champions League Top Scorer',
    img_url:
      'https://gateway.pinata.cloud/ipfs/QmSp1ZxXTiGVSBpoE2VQ4csj1gGEBDicRb2HNvNnJCyQxZ/11-1.png',
  },
  {
    player: `Kaka`,
    season: `2006-2007`,
    team: `AC Millan`,
    card_pack: 1,
    card_color: 1,
    team_record: 'UEFA Champions League',
    man_record: '2007 Ballon dor, UEFA Champions League Top Scorer',
    img_url:
      'https://gateway.pinata.cloud/ipfs/QmSp1ZxXTiGVSBpoE2VQ4csj1gGEBDicRb2HNvNnJCyQxZ/11-2.png',
  },
  {
    player: `Kaka`,
    season: `2006-2007`,
    team: `AC Millan`,
    card_pack: 1,
    card_color: 2,
    team_record: 'UEFA Champions League',
    man_record: '2007 Ballon dor, UEFA Champions League Top Scorer',
    img_url:
      'https://gateway.pinata.cloud/ipfs/QmSp1ZxXTiGVSBpoE2VQ4csj1gGEBDicRb2HNvNnJCyQxZ/11-3.png',
  },
  {
    player: `Robert Lewandowski`,
    season: `2019-2020`,
    team: `Bayern Munchen`,
    card_pack: 1,
    card_color: 0,
    team_record: 'Bundesliga, UEFA Champions League',
    man_record: 'UEFA Champions League Top Scorer, Bundesliga Top Scorer',
    img_url:
      'https://gateway.pinata.cloud/ipfs/QmSp1ZxXTiGVSBpoE2VQ4csj1gGEBDicRb2HNvNnJCyQxZ/12-1.png',
  },
  {
    player: `Robert Lewandowski`,
    season: `2019-2020`,
    team: `Bayern Munchen`,
    card_pack: 1,
    card_color: 1,
    team_record: 'Bundesliga, UEFA Champions League',
    man_record: 'UEFA Champions League Top Scorer, Bundesliga Top Scorer',
    img_url:
      'https://gateway.pinata.cloud/ipfs/QmSp1ZxXTiGVSBpoE2VQ4csj1gGEBDicRb2HNvNnJCyQxZ/12-2.png',
  },
  {
    player: `Robert Lewandowski`,
    season: `2019-2020`,
    team: `Bayern Munchen`,
    card_pack: 1,
    card_color: 2,
    team_record: 'Bundesliga, UEFA Champions League',
    man_record: 'UEFA Champions League Top Scorer, Bundesliga Top Scorer',
    img_url:
      'https://gateway.pinata.cloud/ipfs/QmSp1ZxXTiGVSBpoE2VQ4csj1gGEBDicRb2HNvNnJCyQxZ/12-3.png',
  },
  {
    player: `Zinedine Zidane`,
    season: `2006 world cup`,
    team: `France`,
    card_pack: 1,
    card_color: 0,
    team_record: '',
    man_record: '2006 World Cup Golden Ball',
    img_url:
      'https://gateway.pinata.cloud/ipfs/QmSp1ZxXTiGVSBpoE2VQ4csj1gGEBDicRb2HNvNnJCyQxZ/13-1.png',
  },
  {
    player: `Zinedine Zidane`,
    season: `2006 world cup`,
    team: `France`,
    card_pack: 1,
    card_color: 1,
    team_record: '',
    man_record: '2006 World Cup Golden Ball',
    img_url:
      'https://gateway.pinata.cloud/ipfs/QmSp1ZxXTiGVSBpoE2VQ4csj1gGEBDicRb2HNvNnJCyQxZ/13-2.png',
  },
  {
    player: `Zinedine Zidane`,
    season: `2006 world cup`,
    team: `France`,
    card_pack: 1,
    card_color: 2,
    team_record: '',
    man_record: '2006 World Cup Golden Ball',
    img_url:
      'https://gateway.pinata.cloud/ipfs/QmSp1ZxXTiGVSBpoE2VQ4csj1gGEBDicRb2HNvNnJCyQxZ/13-3.png',
  },
  {
    player: `Ronaldo`,
    season: `2002 world cup`,
    team: `Brazil`,
    card_pack: 1,
    card_color: 0,
    team_record: '2002 World Cup',
    man_record: '2002 Ballon dor, 2002 World Cup Golden Boot',
    img_url:
      'https://gateway.pinata.cloud/ipfs/QmSp1ZxXTiGVSBpoE2VQ4csj1gGEBDicRb2HNvNnJCyQxZ/14-1.png',
  },
  {
    player: `Ronaldo`,
    season: `2002 world cup`,
    team: `Brazil`,
    card_pack: 1,
    card_color: 1,
    team_record: '2002 World Cup',
    man_record: '2002 Ballon dor, 2002 World Cup Golden Boot',
    img_url:
      'https://gateway.pinata.cloud/ipfs/QmSp1ZxXTiGVSBpoE2VQ4csj1gGEBDicRb2HNvNnJCyQxZ/14-2.png',
  },
  {
    player: `Ronaldo`,
    season: `2002 world cup`,
    team: `Brazil`,
    card_pack: 1,
    card_color: 2,
    team_record: '2002 World Cup',
    man_record: '2002 Ballon dor, 2002 World Cup Golden Boot',
    img_url:
      'https://gateway.pinata.cloud/ipfs/QmSp1ZxXTiGVSBpoE2VQ4csj1gGEBDicRb2HNvNnJCyQxZ/14-3.png',
  },
  {
    player: `Luka Modric`,
    season: `2021-2022`,
    team: `Real Madrid`,
    card_pack: 1,
    card_color: 0,
    team_record: 'UEFA Champions League, La Liga',
    man_record: '',
    img_url:
      'https://gateway.pinata.cloud/ipfs/QmSp1ZxXTiGVSBpoE2VQ4csj1gGEBDicRb2HNvNnJCyQxZ/15-1.png',
  },
  {
    player: `Luka Modric`,
    season: `2021-2022`,
    team: `Real Madrid`,
    card_pack: 1,
    card_color: 1,
    team_record: 'UEFA Champions League, La Liga',
    man_record: '',
    img_url:
      'https://gateway.pinata.cloud/ipfs/QmSp1ZxXTiGVSBpoE2VQ4csj1gGEBDicRb2HNvNnJCyQxZ/15-2.png',
  },
  {
    player: `Luka Modric`,
    season: `2021-2022`,
    team: `Real Madrid`,
    card_pack: 1,
    card_color: 2,
    team_record: 'UEFA Champions League, La Liga',
    man_record: '',
    img_url:
      'https://gateway.pinata.cloud/ipfs/QmSp1ZxXTiGVSBpoE2VQ4csj1gGEBDicRb2HNvNnJCyQxZ/15-3.png',
  },
  {
    player: `Courtois`,
    season: `2021-2022`,
    team: `Real Madrid`,
    card_pack: 1,
    card_color: 0,
    team_record: 'UEFA Champions League, La Liga',
    man_record: '',
    img_url:
      'https://gateway.pinata.cloud/ipfs/QmSp1ZxXTiGVSBpoE2VQ4csj1gGEBDicRb2HNvNnJCyQxZ/16-1.png',
  },
  {
    player: `Courtois`,
    season: `2021-2022`,
    team: `Real Madrid`,
    card_pack: 1,
    card_color: 1,
    team_record: 'UEFA Champions League, La Liga',
    man_record: '',
    img_url:
      'https://gateway.pinata.cloud/ipfs/QmSp1ZxXTiGVSBpoE2VQ4csj1gGEBDicRb2HNvNnJCyQxZ/16-2.png',
  },
  {
    player: `Courtois`,
    season: `2021-2022`,
    team: `Real Madrid`,
    card_pack: 1,
    card_color: 2,
    team_record: 'UEFA Champions League, La Liga',
    man_record: '',
    img_url:
      'https://gateway.pinata.cloud/ipfs/QmSp1ZxXTiGVSBpoE2VQ4csj1gGEBDicRb2HNvNnJCyQxZ/16-3.png',
  },
  {
    player: `Tony Kroos`,
    season: `2021-2022`,
    team: `Real Madrid`,
    card_pack: 1,
    card_color: 0,
    team_record: 'UEFA Champions League, La Liga',
    man_record: '',
    img_url:
      'https://gateway.pinata.cloud/ipfs/QmSp1ZxXTiGVSBpoE2VQ4csj1gGEBDicRb2HNvNnJCyQxZ/17-1.png',
  },
  {
    player: `Tony Kroos`,
    season: `2021-2022`,
    team: `Real Madrid`,
    card_pack: 1,
    card_color: 1,
    team_record: 'UEFA Champions League, La Liga',
    man_record: '',
    img_url:
      'https://gateway.pinata.cloud/ipfs/QmSp1ZxXTiGVSBpoE2VQ4csj1gGEBDicRb2HNvNnJCyQxZ/17-2.png',
  },
  {
    player: `Tony Kroos`,
    season: `2021-2022`,
    team: `Real Madrid`,
    card_pack: 1,
    card_color: 2,
    team_record: 'UEFA Champions League, La Liga',
    man_record: '',
    img_url:
      'https://gateway.pinata.cloud/ipfs/QmSp1ZxXTiGVSBpoE2VQ4csj1gGEBDicRb2HNvNnJCyQxZ/17-3.png',
  },
  {
    player: `Vinicius Junior`,
    season: `2021-2022`,
    team: `Real Madrid`,
    card_pack: 1,
    card_color: 0,
    team_record: 'UEFA Champions League, La Liga',
    man_record: '',
    img_url:
      'https://gateway.pinata.cloud/ipfs/QmSp1ZxXTiGVSBpoE2VQ4csj1gGEBDicRb2HNvNnJCyQxZ/18-1.png',
  },
  {
    player: `Vinicius Junior`,
    season: `2021-2022`,
    team: `Real Madrid`,
    card_pack: 1,
    card_color: 1,
    team_record: 'UEFA Champions League, La Liga',
    man_record: '',
    img_url:
      'https://gateway.pinata.cloud/ipfs/QmSp1ZxXTiGVSBpoE2VQ4csj1gGEBDicRb2HNvNnJCyQxZ/18-2.png',
  },
  {
    player: `Vinicius Junior`,
    season: `2021-2022`,
    team: `Real Madrid`,
    card_pack: 1,
    card_color: 2,
    team_record: 'UEFA Champions League, La Liga',
    man_record: '',
    img_url:
      'https://gateway.pinata.cloud/ipfs/QmSp1ZxXTiGVSBpoE2VQ4csj1gGEBDicRb2HNvNnJCyQxZ/18-3.png',
  },
  {
    player: `Federico Valverde`,
    season: `2021-2022`,
    team: `Real Madrid`,
    card_pack: 1,
    card_color: 0,
    team_record: 'UEFA Champions League, La Liga',
    man_record: '',
    img_url:
      'https://gateway.pinata.cloud/ipfs/QmSp1ZxXTiGVSBpoE2VQ4csj1gGEBDicRb2HNvNnJCyQxZ/19-1.png',
  },
  {
    player: `Federico Valverde`,
    season: `2021-2022`,
    team: `Real Madrid`,
    card_pack: 1,
    card_color: 1,
    team_record: 'UEFA Champions League, La Liga',
    man_record: '',
    img_url:
      'https://gateway.pinata.cloud/ipfs/QmSp1ZxXTiGVSBpoE2VQ4csj1gGEBDicRb2HNvNnJCyQxZ/19-2.png',
  },
  {
    player: `Federico Valverde`,
    season: `2021-2022`,
    team: `Real Madrid`,
    card_pack: 1,
    card_color: 2,
    team_record: 'UEFA Champions League, La Liga',
    man_record: '',
    img_url:
      'https://gateway.pinata.cloud/ipfs/QmSp1ZxXTiGVSBpoE2VQ4csj1gGEBDicRb2HNvNnJCyQxZ/19-3.png',
  },
  {
    player: `Casemiro`,
    season: `2021-2022`,
    team: `Real Madrid`,
    card_pack: 1,
    card_color: 0,
    team_record: 'UEFA Champions League, La Liga',
    man_record: '',
    img_url:
      'https://gateway.pinata.cloud/ipfs/QmSp1ZxXTiGVSBpoE2VQ4csj1gGEBDicRb2HNvNnJCyQxZ/20-1.png',
  },
  {
    player: `Casemiro`,
    season: `2021-2022`,
    team: `Real Madrid`,
    card_pack: 1,
    card_color: 1,
    team_record: 'UEFA Champions League, La Liga',
    man_record: '',
    img_url:
      'https://gateway.pinata.cloud/ipfs/QmSp1ZxXTiGVSBpoE2VQ4csj1gGEBDicRb2HNvNnJCyQxZ/20-2.png',
  },
  {
    player: `Casemiro`,
    season: `2021-2022`,
    team: `Real Madrid`,
    card_pack: 1,
    card_color: 2,
    team_record: 'UEFA Champions League, La Liga',
    man_record: '',
    img_url:
      'https://gateway.pinata.cloud/ipfs/QmSp1ZxXTiGVSBpoE2VQ4csj1gGEBDicRb2HNvNnJCyQxZ/20-3.png',
  },
  {
    player: `Eder Militao`,
    season: `2021-2022`,
    team: `Real Madrid`,
    card_pack: 0,
    card_color: 0,
    team_record: 'UEFA Champions League, La Liga',
    man_record: '',
    img_url:
      'https://gateway.pinata.cloud/ipfs/QmSp1ZxXTiGVSBpoE2VQ4csj1gGEBDicRb2HNvNnJCyQxZ/21-1.png',
  },
  {
    player: `Eder Militao`,
    season: `2021-2022`,
    team: `Real Madrid`,
    card_pack: 0,
    card_color: 1,
    img_url:
      'https://gateway.pinata.cloud/ipfs/QmSp1ZxXTiGVSBpoE2VQ4csj1gGEBDicRb2HNvNnJCyQxZ/21-2.png',
  },
  {
    player: `Eder Militao`,
    season: `2021-2022`,
    team: `Real Madrid`,
    card_pack: 0,
    card_color: 2,
    team_record: 'UEFA Champions League, La Liga',
    man_record: '',
    img_url:
      'https://gateway.pinata.cloud/ipfs/QmSp1ZxXTiGVSBpoE2VQ4csj1gGEBDicRb2HNvNnJCyQxZ/21-3.png',
  },
  {
    player: `David Alaba`,
    season: `2021-2022`,
    team: `Real Madrid`,
    card_pack: 0,
    card_color: 0,
    team_record: 'UEFA Champions League, La Liga',
    man_record: '',
    img_url:
      'https://gateway.pinata.cloud/ipfs/QmSp1ZxXTiGVSBpoE2VQ4csj1gGEBDicRb2HNvNnJCyQxZ/22-1.png',
  },
  {
    player: `David Alaba`,
    season: `2021-2022`,
    team: `Real Madrid`,
    card_pack: 0,
    card_color: 1,
    team_record: 'UEFA Champions League, La Liga',
    man_record: '',
    img_url:
      'https://gateway.pinata.cloud/ipfs/QmSp1ZxXTiGVSBpoE2VQ4csj1gGEBDicRb2HNvNnJCyQxZ/22-2.png',
  },
  {
    player: `David Alaba`,
    season: `2021-2022`,
    team: `Real Madrid`,
    card_pack: 0,
    card_color: 2,
    team_record: 'UEFA Champions League, La Liga',
    man_record: '',
    img_url:
      'https://gateway.pinata.cloud/ipfs/QmSp1ZxXTiGVSBpoE2VQ4csj1gGEBDicRb2HNvNnJCyQxZ/22-3.png',
  },

  {
    player: `Daniel Carvajal`,
    season: `2021-2022`,
    team: `Real Madrid`,
    card_pack: 0,
    card_color: 0,
    team_record: 'UEFA Champions League, La Liga',
    man_record: '',
    img_url:
      'https://gateway.pinata.cloud/ipfs/QmSp1ZxXTiGVSBpoE2VQ4csj1gGEBDicRb2HNvNnJCyQxZ/23-1.png',
  },
  {
    player: `Daniel Carvajal`,
    season: `2021-2022`,
    team: `Real Madrid`,
    card_pack: 0,
    card_color: 1,
    team_record: 'UEFA Champions League, La Liga',
    man_record: '',
    img_url:
      'https://gateway.pinata.cloud/ipfs/QmSp1ZxXTiGVSBpoE2VQ4csj1gGEBDicRb2HNvNnJCyQxZ/23-2.png',
  },
  {
    player: `Daniel Carvajal`,
    season: `2021-2022`,
    team: `Real Madrid`,
    card_pack: 0,
    card_color: 2,
    team_record: 'UEFA Champions League, La Liga',
    man_record: '',
    img_url:
      'https://gateway.pinata.cloud/ipfs/QmSp1ZxXTiGVSBpoE2VQ4csj1gGEBDicRb2HNvNnJCyQxZ/23-3.png',
  },
  {
    player: `Ferland Mendy`,
    season: `2021-2022`,
    team: `Real Madrid`,
    card_pack: 0,
    card_color: 0,
    team_record: 'UEFA Champions League, La Liga',
    man_record: '',
    img_url:
      'https://gateway.pinata.cloud/ipfs/QmSp1ZxXTiGVSBpoE2VQ4csj1gGEBDicRb2HNvNnJCyQxZ/24-1.png',
  },
  {
    player: `Ferland Mendy`,
    season: `2021-2022`,
    team: `Real Madrid`,
    card_pack: 0,
    card_color: 1,
    team_record: 'UEFA Champions League, La Liga',
    man_record: '',
    img_url:
      'https://gateway.pinata.cloud/ipfs/QmSp1ZxXTiGVSBpoE2VQ4csj1gGEBDicRb2HNvNnJCyQxZ/24-2.png',
  },
  {
    player: `Ferland Mendy`,
    season: `2021-2022`,
    team: `Real Madrid`,
    card_pack: 0,
    card_color: 2,
    team_record: 'UEFA Champions League, La Liga',
    man_record: '',
    img_url:
      'https://gateway.pinata.cloud/ipfs/QmSp1ZxXTiGVSBpoE2VQ4csj1gGEBDicRb2HNvNnJCyQxZ/24-3.png',
  },
  {
    player: `Fernando Torres`,
    season: `2007-2008`,
    team: `Liverpool`,
    card_pack: 0,
    card_color: 0,
    team_record: '',
    man_record: '',
    img_url:
      'https://gateway.pinata.cloud/ipfs/QmSp1ZxXTiGVSBpoE2VQ4csj1gGEBDicRb2HNvNnJCyQxZ/25-1.png',
  },
  {
    player: `Fernando Torres`,
    season: `2007-2008`,
    team: `Liverpool`,
    card_pack: 0,
    card_color: 1,
    team_record: '',
    man_record: '',
    img_url:
      'https://gateway.pinata.cloud/ipfs/QmSp1ZxXTiGVSBpoE2VQ4csj1gGEBDicRb2HNvNnJCyQxZ/25-2.png',
  },
  {
    player: `Fernando Torres`,
    season: `2007-2008`,
    team: `Liverpool`,
    card_pack: 0,
    card_color: 2,
    team_record: '',
    man_record: '',
    img_url:
      'https://gateway.pinata.cloud/ipfs/QmSp1ZxXTiGVSBpoE2VQ4csj1gGEBDicRb2HNvNnJCyQxZ/25-3.png',
  },
  {
    player: `Steven Gerrard`,
    season: `2004-2005`,
    team: `Liverpool`,
    card_pack: 0,
    card_color: 0,
    team_record: 'UEFA Champions League',
    man_record: '',
    img_url:
      'https://gateway.pinata.cloud/ipfs/QmSp1ZxXTiGVSBpoE2VQ4csj1gGEBDicRb2HNvNnJCyQxZ/26-1.png',
  },
  {
    player: `Steven Gerrard`,
    season: `2004-2005`,
    team: `Liverpool`,
    card_pack: 0,
    card_color: 1,
    team_record: 'UEFA Champions League',
    man_record: '',
    img_url:
      'https://gateway.pinata.cloud/ipfs/QmSp1ZxXTiGVSBpoE2VQ4csj1gGEBDicRb2HNvNnJCyQxZ/26-2.png',
  },
  {
    player: `Steven Gerrard`,
    season: `2004-2005`,
    team: `Liverpool`,
    card_pack: 0,
    card_color: 2,
    team_record: 'UEFA Champions League',
    man_record: '',
    img_url:
      'https://gateway.pinata.cloud/ipfs/QmSp1ZxXTiGVSBpoE2VQ4csj1gGEBDicRb2HNvNnJCyQxZ/26-3.png',
  },
  {
    player: `Thierry Henry`,
    season: `2003-2004`,
    team: `Arsenal`,
    card_pack: 0,
    card_color: 0,
    team_record: 'Premier League',
    man_record: 'Premeir League Top Scorer',
    img_url:
      'https://gateway.pinata.cloud/ipfs/QmSp1ZxXTiGVSBpoE2VQ4csj1gGEBDicRb2HNvNnJCyQxZ/27-1.png',
  },
  {
    player: `Thierry Henry`,
    season: `2003-2004`,
    team: `Arsenal`,
    card_pack: 0,
    card_color: 1,
    team_record: 'Premier League',
    man_record: 'Premeir League Top Scorer',
    img_url:
      'https://gateway.pinata.cloud/ipfs/QmSp1ZxXTiGVSBpoE2VQ4csj1gGEBDicRb2HNvNnJCyQxZ/27-2.png',
  },
  {
    player: `Thierry Henry`,
    season: `2003-2004`,
    team: `Arsenal`,
    card_pack: 0,
    card_color: 2,
    team_record: 'Premier League',
    man_record: 'Premeir League Top Scorer',
    img_url:
      'https://gateway.pinata.cloud/ipfs/QmSp1ZxXTiGVSBpoE2VQ4csj1gGEBDicRb2HNvNnJCyQxZ/27-3.png',
  },
  {
    player: `Wayne Rooney`,
    season: `2009-2010`,
    team: `Manchester United`,
    card_pack: 0,
    card_color: 0,
    team_record: '',
    man_record: '',
    img_url:
      'https://gateway.pinata.cloud/ipfs/QmSp1ZxXTiGVSBpoE2VQ4csj1gGEBDicRb2HNvNnJCyQxZ/28-1.png',
  },
  {
    player: `Wayne Rooney`,
    season: `2009-2010`,
    team: `Manchester United`,
    card_pack: 0,
    card_color: 1,
    team_record: '',
    man_record: '',
    img_url:
      'https://gateway.pinata.cloud/ipfs/QmSp1ZxXTiGVSBpoE2VQ4csj1gGEBDicRb2HNvNnJCyQxZ/28-2.png',
  },
  {
    player: `Wayne Rooney`,
    season: `2009-2010`,
    team: `Manchester United`,
    card_pack: 0,
    card_color: 2,
    team_record: '',
    man_record: '',
    img_url:
      'https://gateway.pinata.cloud/ipfs/QmSp1ZxXTiGVSBpoE2VQ4csj1gGEBDicRb2HNvNnJCyQxZ/28-3.png',
  },
  {
    player: `Kylian Mbappe`,
    season: `2018 world cup`,
    team: `France`,
    card_pack: 0,
    card_color: 0,
    team_record: '2018 World Cup',
    man_record: '2018 World Cup Best Young Player',
    img_url:
      'https://gateway.pinata.cloud/ipfs/QmSp1ZxXTiGVSBpoE2VQ4csj1gGEBDicRb2HNvNnJCyQxZ/29-1.png',
  },
  {
    player: `Kylian Mbappe`,
    season: `2018 world cup`,
    team: `France`,
    card_pack: 0,
    card_color: 1,
    team_record: '2018 World Cup',
    man_record: '2018 World Cup Best Young Player',
    img_url:
      'https://gateway.pinata.cloud/ipfs/QmSp1ZxXTiGVSBpoE2VQ4csj1gGEBDicRb2HNvNnJCyQxZ/29-2.png',
  },
  {
    player: `Kylian Mbappe`,
    season: `2018 world cup`,
    team: `France`,
    card_pack: 0,
    card_color: 2,
    team_record: '2018 World Cup',
    man_record: '2018 World Cup Best Young Player',
    img_url:
      'https://gateway.pinata.cloud/ipfs/QmSp1ZxXTiGVSBpoE2VQ4csj1gGEBDicRb2HNvNnJCyQxZ/29-3.png',
  },
  {
    player: `Neymar`,
    season: `2019-2020`,
    team: `PSG`,
    card_pack: 0,
    card_color: 0,
    team_record: 'League 1',
    man_record: '',
    img_url:
      'https://gateway.pinata.cloud/ipfs/QmSp1ZxXTiGVSBpoE2VQ4csj1gGEBDicRb2HNvNnJCyQxZ/30-1.png',
  },
  {
    player: `Neymar`,
    season: `2019-2020`,
    team: `PSG`,
    card_pack: 0,
    card_color: 1,
    team_record: 'League 1',
    man_record: '',
    img_url:
      'https://gateway.pinata.cloud/ipfs/QmSp1ZxXTiGVSBpoE2VQ4csj1gGEBDicRb2HNvNnJCyQxZ/30-2.png',
  },
  {
    player: `Neymar`,
    season: `2019-2020`,
    team: `PSG`,
    card_pack: 0,
    card_color: 2,
    team_record: 'League 1',
    man_record: '',
    img_url:
      'https://gateway.pinata.cloud/ipfs/QmSp1ZxXTiGVSBpoE2VQ4csj1gGEBDicRb2HNvNnJCyQxZ/30-3.png',
  },
];
